name: "Slack Build"
on:
  workflow_dispatch:

jobs:
  package:
    strategy:
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        go-version: [1.22]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies on Linux
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential libgtk-3-dev libpcap-dev libwebkit2gtk-4.1-dev

      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Wails app on Ubuntu
        if: matrix.platform == 'ubuntu-latest'
        run: wails build -tags webkit2_41

      - name: Build Wails app on Other Platforms
        if: matrix.platform != 'ubuntu-latest'
        run: wails build

      - name: Upload Artifacts macOS
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v2
        with:
          name: Slack-macos-amd64
          path: build/bin/*

      - name: Upload Artifacts Windows
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: Slack-windows-amd64
          path: build/bin/*

      - name: Upload Artifacts Linux
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: Slack-linux-amd64
          path: build/bin/*
