name: "Slack for windows amd64"
on:
  workflow_dispatch:

jobs:
  package:
    strategy:
      matrix:
        platform: [windows-latest]
        go-version: [1.22]
        arch: [amd64]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Wails app on windows
        run: wails build -platform windows/${{ matrix.arch }}

      - name: Upload Artifacts windows
        uses: actions/upload-artifact@v4
        with:
          name: Slack-windows-amd64
          path: build/bin/*