name: "Slack Build"
on:
  workflow_dispatch:

jobs:
  package:
    strategy:
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        go-version: [1.22]
        arch: [amd64, arm64]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies on Linux
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential libgtk-3-dev libpcap-dev libwebkit2gtk-4.1-dev

      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Wails app on Ubuntu
        if: matrix.platform == 'ubuntu-latest'
        run: |
          if [ "${{ matrix.arch }}" == "arm64" ]; then
            GOARCH=arm64 wails build -tags webkit2_41
          else
            wails build -tags webkit2_41
          fi

      - name: Build Wails app on macOS
        if: matrix.platform == 'macos-latest'
        run: |
          if [ "${{ matrix.arch }}" == "arm64" ]; then
            GOARCH=arm64 wails build
          else
            wails build
          fi

      - name: Build Wails app on Windows
        if: matrix.platform == 'windows-latest'
        run: |
          if [ "${{ matrix.arch }}" == "arm64" ]; then
            GOARCH=arm64 wails build
          else
            wails build
          fi

      - name: Upload Artifacts macOS
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v2
        with:
          name: Slack-macos-${{ matrix.arch }}
          path: build/bin/*

      - name: Upload Artifacts Windows
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: Slack-windows-${{ matrix.arch }}
          path: build/bin/*

      - name: Upload Artifacts Linux
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: Slack-linux-${{ matrix.arch }}
          path: build/bin/*
