name: "Slack Build"
on:
  workflow_dispatch:

jobs:
  package:
    strategy:
      matrix:
        platform: [windows-latest]
        go-version: [1.22]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Upload Artifacts Windows
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: Slack-windows-amd64
          path: build/bin/*

